on: [push, pull_request]

name: ghci

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: rstudio/r-base:3.6-bionic
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: Install package dependencies
        run: Rscript -e "install.packages(c('remotes', 'rcmdcheck', 'pkgdown'))" -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'error')"
#      - name: Document Package
#        run: |
#          Rscript -e "pkgdown::build_site(override = list(devel = FALSE, external = FALSE))"
#      - name: Deploy to GitHub Pages
#        if: github.ref == 'refs/heads/master'
#        uses: maxheld83/ghpages@v0.2.0
#        env:
#          BUILD_DIR: docs
#          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Test coverage
#        if: matrix.config.os == 'macOS-latest' && matrix.config.r == '3.6'
        run: |
          Rscript -e 'covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")'
